version: '3'
services:
  gitbucket:
    build:
      context: .
      args:
        gitbucket_version: "4.31.2"
    image: hyt/gitbucket:4.31.2
    container_name: gitbucket
    ports:
      - "8888:8080"
    volumes:
      - ./gitbucket:/gitbucket
